preload=/home/oberg/.dotfiles/bg3.png
preload=/home/oberg/.dotfiles/bg_center.png
preload=/home/oberg/.dotfiles/bg_sides.png

wallpaper=eDP-1,/home/oberg/.dotfiles/bg3.png
wallpaper=DP-1,/home/oberg/.dotfiles/bg_sides.png
wallpaper=DP-2,/home/oberg/.dotfiles/bg_center.png
wallpaper=HDMI-A-1,/home/oberg/.dotfiles/bg_sides.png

ipc=true
