# Appearance settings
font pango:JetBrainsMono Nerd Font 10

# Window borders
default_border pixel 2
default_floating_border pixel 2

# Colors (Gruvbox theme)
client.focused          #504945 #504945 #ebdbb2 #504945 #ebdbb2
client.focused_inactive #3c3836 #3c3836 #bdae93 #3c3836 #504945
client.unfocused        #3c3836 #3c3836 #bdae93 #3c3836 #504945
client.urgent           #cc241d #cc241d #ebdbb2 #cc241d #ebdbb2
client.placeholder      #3c3836 #3c3836 #bdae93 #3c3836 #504945

client.background       #282828
