[ColorScheme]
window=282828
windowText=ebdbb2
base=3c3836
text=ebdbb2
button=504945
buttonText=ebdbb2
brightText=fbf1c7
link=83a598
linkVisited=d3869b
highlight=83a598
highlightedText=282828
alternateBase=3c3836
tooltipBase=282828
tooltipText=ebdbb2
